swagger: "2.0"

definitions:
  vo.ConfigVo:
    properties:
      chain_id:
        type: string
      env:
        type: string
      host:
        type: string
      network_name:
        type: string
      node_version:
        type: string
      show_faucet:
        type: integer
      tendermint_version:
        type: string
      umeng_id:
        type: integer
    type: object
  vo.EnvConfig:
    properties:
      chain_id:
        type: string
      configs:
        items:
          $ref: '#/definitions/vo.ConfigVo'
        type: array
      cur_env:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/config:
    get:
      consumes:
      - application/json
      description: get config
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.EnvConfig'
            type: object
      summary: config
      tags:
      - common



