definitions:
  utils.Coin:
    properties:
      amount:
        type: number
      denom:
        type: string
    type: object
  utils.CoinAsStr:
    properties:
      amount:
        type: string
      denom:
        type: string
    type: object
  utils.Coins:
    items:
      properties:
        amount:
          type: number
        denom:
          type: string
      type: object
    type: array
  utils.CoinsAsStr:
    items:
      properties:
        amount:
          type: string
        denom:
          type: string
      type: object
    type: array
  vo.AccountDelegationsRespond:
    items:
      properties:
        address:
          type: string
        amount:
          $ref: '#/definitions/utils.Coin'
          type: object
        height:
          type: string
        moniker:
          type: string
        shares:
          type: string
      type: object
    type: array
  vo.AccountDelegationsVo:
    properties:
      address:
        type: string
      amount:
        $ref: '#/definitions/utils.Coin'
        type: object
      height:
        type: string
      moniker:
        type: string
      shares:
        type: string
    type: object
  vo.AccountInfo:
    properties:
      address:
        type: string
      balance:
        items:
          $ref: '#/definitions/utils.Coin'
        type: array
      percent:
        type: number
      rank:
        type: integer
      update_at:
        type: integer
    type: object
  vo.AccountRewardsVo:
    properties:
      commission_rewards:
        $ref: '#/definitions/utils.CoinsAsStr'
        type: object
      delagations_rewards:
        items:
          $ref: '#/definitions/vo.DelagationsRewards'
        type: array
      total_rewards:
        $ref: '#/definitions/utils.CoinsAsStr'
        type: object
    type: object
  vo.AccountUnbondingDelegationsRespond:
    items:
      properties:
        address:
          type: string
        amount:
          $ref: '#/definitions/utils.Coin'
          type: object
        end_time:
          type: string
        height:
          type: string
        moniker:
          type: string
      type: object
    type: array
  vo.AccountUnbondingDelegationsVo:
    properties:
      address:
        type: string
      amount:
        $ref: '#/definitions/utils.Coin'
        type: object
      end_time:
        type: string
      height:
        type: string
      moniker:
        type: string
    type: object
  vo.AccountVo:
    properties:
      address:
        type: string
      amount:
        $ref: '#/definitions/utils.Coins'
        type: object
      deposits:
        $ref: '#/definitions/utils.Coin'
        type: object
      isProfiler:
        type: boolean
      moniker:
        type: string
      operator_address:
        type: string
      status:
        type: string
      withdrawAddress:
        type: string
    type: object
  vo.AccountsInfoRespond:
    items:
      properties:
        address:
          type: string
        balance:
          items:
            $ref: '#/definitions/utils.Coin'
          type: array
        percent:
          type: number
        rank:
          type: integer
        update_at:
          type: integer
      type: object
    type: array
  vo.ActualFee:
    properties:
      amount:
        type: number
      denom:
        type: string
    type: object
  vo.AssetGateways:
    properties:
      details:
        type: string
      icons:
        type: string
      identity:
        type: string
      moniker:
        type: string
      owner:
        type: string
      website:
        type: string
    type: object
  vo.AssetTokens:
    properties:
      asset_gateway:
        $ref: '#/definitions/vo.AssetGateways'
        type: object
      canonical_symbol:
        type: string
      decimal:
        type: integer
      family:
        type: string
      gateway:
        type: string
      initial_supply:
        type: string
      max_supply:
        type: string
      min_unit_alias:
        type: string
      mintable:
        type: boolean
      name:
        type: string
      owner:
        type: string
      source:
        type: string
      symbol:
        type: string
      token_id:
        type: string
      total_supply:
        type: string
    type: object
  vo.AssetTokensRespond:
    items:
      properties:
        asset_gateway:
          $ref: '#/definitions/vo.AssetGateways'
          type: object
        canonical_symbol:
          type: string
        decimal:
          type: integer
        family:
          type: string
        gateway:
          type: string
        initial_supply:
          type: string
        max_supply:
          type: string
        min_unit_alias:
          type: string
        mintable:
          type: boolean
        name:
          type: string
        owner:
          type: string
        source:
          type: string
        symbol:
          type: string
        token_id:
          type: string
        total_supply:
          type: string
      type: object
    type: array
  vo.AssetsRespond:
    properties:
      asset_type:
        type: string
      total:
        type: integer
      txs:
        items:
          $ref: '#/definitions/vo.AssetsVo'
        type: array
    type: object
  vo.AssetsVo:
    properties:
      amount:
        type: integer
      canonical_symbol:
        type: string
      decimal:
        type: integer
      dst_owner:
        type: string
      gateway:
        type: string
      height:
        type: integer
      initial_supply:
        type: integer
      max_supply:
        type: integer
      mint_to:
        type: string
      mintable:
        type: boolean
      name:
        type: string
      owner:
        type: string
      src_owner:
        type: string
      symbol:
        type: string
      symbol_min:
        type: string
      timestamp:
        type: string
      token_id:
        type: string
      tx_fee:
        $ref: '#/definitions/vo.ActualFee'
        type: object
      tx_hash:
        type: string
      tx_status:
        type: string
      type:
        type: string
    type: object
  vo.BlockForList:
    properties:
      height:
        type: integer
      precommit_validator_num:
        type: integer
      precommit_voting_power:
        type: integer
      proposer_as_validator_addr:
        type: string
      proposer_moniker:
        type: string
      timestamp:
        type: string
      txs_num:
        type: integer
      validator_num_for_height:
        type: integer
      voting_power_for_height:
        type: integer
    type: object
  vo.BlockForListRespond:
    items:
      properties:
        height:
          type: integer
        precommit_validator_num:
          type: integer
        precommit_voting_power:
          type: integer
        proposer_as_validator_addr:
          type: string
        proposer_moniker:
          type: string
        timestamp:
          type: string
        txs_num:
          type: integer
        validator_num_for_height:
          type: integer
        voting_power_for_height:
          type: integer
      type: object
    type: array
  vo.BlockInfo:
    properties:
      block_hash:
        type: string
      block_height:
        type: string
      latest_height:
        type: string
      mint_coin:
        $ref: '#/definitions/utils.Coin'
        type: object
      precommit_validator_num:
        type: object
      precommit_voting_power:
        type: object
      propopser_addr:
        type: string
      propopser_moniker:
        type: string
      timestamp:
        type: string
      total_validator_num:
        type: integer
      total_voting_power:
        type: integer
      transactions:
        type: string
    type: object
  vo.BlockInfoVo:
    properties:
      hash:
        type: string
      height:
        type: integer
      last_block_hash:
        type: string
      last_commit:
        items:
          type: string
        type: array
      num_txs:
        type: integer
      time:
        type: string
      total_txs:
        type: integer
      validators:
        items:
          $ref: '#/definitions/vo.ValInfo'
        type: array
    type: object
  vo.BlockInfoVoRespond:
    items:
      properties:
        hash:
          type: string
        height:
          type: integer
        last_block_hash:
          type: string
        last_commit:
          items:
            type: string
          type: array
        num_txs:
          type: integer
        time:
          type: string
        total_txs:
          type: integer
        validators:
          items:
            $ref: '#/definitions/vo.ValInfo'
          type: array
      type: object
    type: array
  vo.BlockValidator:
    properties:
      consensus:
        type: string
      is_proposer:
        type: boolean
      moniker:
        type: string
      operator_address:
        type: string
      proposer_priority:
        type: string
      voting_power:
        type: string
    type: object
  vo.DelagationsRewards:
    properties:
      address:
        type: string
      amount:
        $ref: '#/definitions/utils.CoinsAsStr'
        type: object
      moniker:
        type: string
    type: object
  vo.ValInfo:
    properties:
      address:
        type: string
      voting_power:
        type: integer
    type: object
  vo.ValidatorSet:
    properties:
      items:
        items:
          $ref: '#/definitions/vo.BlockValidator'
        type: array
      total:
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/account/{address}:
    get:
      consumes:
      - application/json
      description: get detail of account
      parameters:
      - description: account address
        in: path
        name: address
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.AccountVo'
            type: object
      summary: detail
      tags:
      - account
  /api/account/{address}/delegations:
    get:
      consumes:
      - application/json
      description: get delegations of account
      parameters:
      - description: account address
        in: path
        name: address
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.AccountDelegationsRespond'
            type: object
      summary: list
      tags:
      - account
  /api/account/{address}/rewards:
    get:
      consumes:
      - application/json
      description: get rewards of account
      parameters:
      - description: account address
        in: path
        name: address
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.AccountRewardsVo'
            type: object
      summary: list
      tags:
      - account
  /api/account/{address}/unbonding_delegations:
    get:
      consumes:
      - application/json
      description: get unbondingdelegations of account
      parameters:
      - description: account address
        in: path
        name: address
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.AccountUnbondingDelegationsRespond'
            type: object
      summary: list
      tags:
      - account
  /api/accounts:
    get:
      consumes:
      - application/json
      description: get list of account
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.AccountsInfoRespond'
            type: object
      summary: list
      tags:
      - account
  /api/asset/gateways/{moniker}:
    get:
      consumes:
      - application/json
      description: get gateway assets token detail
      parameters:
      - description: moniker
        in: path
        name: moniker
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.AssetGateways'
            type: object
      summary: detail
      tags:
      - assets
  /api/asset/tokens:
    get:
      consumes:
      - application/json
      description: get asset tokens
      parameters:
      - description: source
        in: query
        name: source
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.AssetTokensRespond'
            type: object
      summary: list
      tags:
      - assets
  /api/asset/tokens/{token_id}:
    get:
      consumes:
      - application/json
      description: get assets token detail
      parameters:
      - description: token_id
        in: path
        name: token_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.AssetTokens'
            type: object
      summary: detail
      tags:
      - assets
  /api/assets/gateway/txs:
    get:
      consumes:
      - application/json
      description: get assets txs
      parameters:
      - description: page num
        in: query
        name: page
        required: true
        type: integer
      - description: page size
        in: query
        name: size
        required: true
        type: integer
      - description: txs type
        in: query
        name: tx_type
        type: string
      - description: asset symbol
        in: query
        name: symbol
        type: string
      - description: gateway
        in: query
        name: gateway
        type: string
      - description: moniker
        in: query
        name: moniker
        type: string
      - description: if used count
        enum:
        - "true"
        - "false"
        in: query
        name: total
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.AssetsRespond'
            type: object
      summary: gateway
      tags:
      - assets
  /api/assets/native/txs:
    get:
      consumes:
      - application/json
      description: get assets txs
      parameters:
      - description: page num
        in: query
        name: page
        required: true
        type: integer
      - description: page size
        in: query
        name: size
        required: true
        type: integer
      - description: txs type
        in: query
        name: tx_type
        type: string
      - description: asset symbol
        in: query
        name: symbol
        type: string
      - description: if used count
        enum:
        - "true"
        - "false"
        in: query
        name: total
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.AssetsRespond'
            type: object
      summary: native
      tags:
      - assets
  /api/block/blockinfo/{height}:
    get:
      consumes:
      - application/json
      description: get block info
      parameters:
      - description: block height
        in: path
        name: height
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.BlockInfo'
            type: object
      summary: detail
      tags:
      - block
  /api/block/latestheight:
    get:
      consumes:
      - application/json
      description: get block latestheight
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/int64'
            type: object
      summary: latest
      tags:
      - block
  /api/block/validatorset/{height}:
    get:
      consumes:
      - application/json
      description: get  block validatorset
      parameters:
      - description: page num
        in: query
        name: page
        required: true
        type: integer
      - description: page size
        in: query
        name: size
        required: true
        type: integer
      - description: block height
        in: path
        name: height
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.ValidatorSet'
            type: object
      summary: block validatorset
      tags:
      - block
  /api/blocks:
    get:
      consumes:
      - application/json
      description: get blocks
      parameters:
      - description: page num
        in: query
        name: page
        required: true
        type: integer
      - description: page size
        in: query
        name: size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.BlockForListRespond'
            type: object
      summary: list
      tags:
      - block
  /api/blocks/recent:
    get:
      consumes:
      - application/json
      description: get recent blocks
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.BlockInfoVoRespond'
            type: object
      summary: blocks recent
      tags:
      - block
