swagger: "2.0"
definitions:
  utils.Coin:
    properties:
      amount:
        type: number
      denom:
        type: string
    type: object
  utils.CoinAsStr:
    properties:
      amount:
        type: string
      denom:
        type: string
    type: object
  utils.CoinsAsStr:
    items:
      properties:
        amount:
          type: string
        denom:
          type: string
      type: object
    type: array
  vo.AccountRewardsVo:
    properties:
      commission_rewards:
        $ref: '#/definitions/utils.CoinsAsStr'
        type: object
      delagations_rewards:
        items:
          $ref: '#/definitions/vo.DelagationsRewards'
        type: array
      total_rewards:
        $ref: '#/definitions/utils.CoinsAsStr'
        type: object
    type: object
  vo.AccountUnbondingDelegationsRespond:
    items:
      properties:
        address:
          type: string
        amount:
          $ref: '#/definitions/utils.Coin'
          type: object
        end_time:
          type: string
        height:
          type: string
        moniker:
          type: string
      type: object
    type: array
  vo.AccountUnbondingDelegationsVo:
    properties:
      address:
        type: string
      amount:
        $ref: '#/definitions/utils.Coin'
        type: object
      end_time:
        type: string
      height:
        type: string
      moniker:
        type: string
    type: object
  vo.DelagationsRewards:
    properties:
      address:
        type: string
      amount:
        $ref: '#/definitions/utils.CoinsAsStr'
        type: object
      moniker:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/account/{address}/rewards:
    get:
      consumes:
      - application/json
      description: get rewards of account
      parameters:
      - description: account address
        in: path
        name: address
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.AccountRewardsVo'
            type: object
      summary: list
      tags:
      - account
  /api/account/{address}/unbonding_delegations:
    get:
      consumes:
      - application/json
      description: get unbondingdelegations of account
      parameters:
      - description: account address
        in: path
        name: address
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.AccountUnbondingDelegationsRespond'
            type: object
      summary: list
      tags:
      - account
