version : '2'

services:
    irisplorer:
              image: irisplorer:0.1.0
              container_name: irisplorer
              command: sh -c "irisplorer rest-server --node=tcp://47.104.155.125:46757 --chain-id=pangu --mgo-url=\"mongo:27017\""
              networks:
                      - irisplorernet
    mongo:
              image: mongo
              container_name: mongo
              ports:
                      - 27017:27017
              volumes:
                      - /Users/zhangzhiqiang/volumes/mongo:/data/db
              networks:
                      - irisplorernet

    irisplorer-ui:
              image: irisplorer-ui:0.1.0
              container_name: irisplorer-ui
              command: sh -c "yarn start"
              ports:
                      - 3000:3000
              networks:
                      - irisplorernet
networks:
    irisplorernet:
          external:
                name: irisplorernet
